PRODUCT_ACTIONS_RECEIVER = "product_actions#product_actions"
PRODUCT_ACTIONS_BUY_BUTTON = "buy_button"

PRODUCT_ACTIONS_SET_RECEIVER_MESSAGE_ID = "product_actions_set_receiver_message_id"
PRODUCT_ACTIONS_SET_ENABLED_MESSAGE_ID = "product_actions_set_enabled_message_id"
PRODUCT_ACTIONS_BUTTON_PRESSED = "product_actions_button_pressed"
