PURCHASE_ACTIONS_RECEIVER = "purchase_actions#purchase_actions"
PURCHASE_ACTIONS_CONFIRM_BUTTON = "confirm_button"
PURCHASE_ACTIONS_DELETE_BUTTON = "delete_button"
PURCHASE_ACTIONS_INFO_BUTTON = "info_button"

PURCHASE_ACTIONS_SET_RECEIVER_MESSAGE_ID = "purchase_actions_set_receiver_message_id"
PURCHASE_ACTIONS_SET_ENABLED_MESSAGE_ID = "purchase_actions_set_enabled_message_id"
PURCHASE_ACTIONS_BUTTON_PRESSED = "purchase_actions_button_pressed"
