#pragma once

// X-macro lists: (KEY, VALUE_INT)

#define BILLING_ENUM_PRODUCT_STATUS(X) \
X(ACTIVE, 0) \
X(INACTIVE, 1)

#define BILLING_ENUM_PRODUCT_TYPE(X) \
X(NON_CONSUMABLE, 0) \
X(CONSUMABLE, 1) \
X(SUBSCRIPTION, 2)

#define BILLING_ENUM_PURCHASE_STATE(X) \
X(CREATED, 0) \
X(INVOICE_CREATED, 1) \
X(CONFIRMED, 2) \
X(PAID, 3) \
X(CANCELLED, 4) \
X(CONSUMED, 5) \
X(CLOSED, 6) \
X(PAUSED, 7) \
X(TERMINATED, 8)

#define BILLING_ENUM_THEME(X) \
X(DARK, 0) \
X(LIGHT, 1)
